### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by Choppra** [Nizarii/arma-rcon-class-php#19]
Is there anyway to get chat?  Would that be possible?

**Comment by felixms** [comment]
The chat is broadcasted to all connected clients. However displaying the chat is not possible with ARC, because it does not respond to received packages from the BE server. _(See #18)_
 Even if this is done, you won't get very far, because PHP is not a  suitable language for this situation. You would have to use some kind of daemon and check for packages every second. You would better use NodeJs, Golang or other programming languages.

**Comment by MightySCollins** [comment]
If you REALLY wanted to integrate it and use PHP it might be an idea to have a CLI process with a constant connection which exposes an API or writes to a file/database. Or a websocket which keeps a connection to the server open (not sure how well this would scale).

If you do go down the websocket route let me know as I would be very interested.
