### ISSUE TITLE
Chat 

### ISSUE THREAD

**Issue by nerdalertdk** [Nizarii/arma-rcon-class-php#2]
Hi

Would it be able get the In game chat ? 
Like if someone call's for an admin ?

**Comment by felixms** [comment]
Unfortunately the chat is not handled via RCon, so there is no direct way for retrieving it.

**Comment by Memphis017** [comment]
Yes it is, server is broadcasting chat message to all connected RCon clients, but you need to stay connected to retrieve those, so it's not possible only in php (= ajax needed).

**Comment by felixms** [comment]
@Memphis017 Alright, thanks for this information. Ajax is not necessarily needed, you can use a [daemon](https://github.com/shaneharter/PHP-Daemon) and a [websocket](http://socketo.me/). Of course, this isn't the best solution for such a scenario, because there are, as you said, other programming languages, which do better. Anyway, this is propably the easiest way for a chat protocol fully done in PHP.

**Comment by steffalon** [comment]
Hey @schaeferfelix , do I have to use **getSocket()** function to get the chat/rcon logs? I know it will return a stream resource but how do I make it constant? I have tried to use reactphp loops/streams but it looks like when I ran **getSocket()** every time it will only send it once and not the whole stream. I only get **"logged in"** responds but then it stops executing further. Do I have to change something to keep it constantly connected?
